import {
  BookOpen,
  Box,
  Brain,
  Camera,
  Code,
  Eye,
  Cpu,
  Filter,
  FlaskConical,
  Grid3x3,
  Layers,
  LineChart,
  Scan,
  Shapes,
  Sparkles,
  Target,
  Waves,
  Zap,
} from 'lucide-react'
import type { ChapterMeta } from '@/types/course'

export type ImageLevel = {
  id: number
  title: string
  subtitle: string
}

export const imageLevels: ImageLevel[] = [
  { id: 1, title: 'Partie I', subtitle: 'Fondements atomiques' },
  { id: 2, title: 'Partie II', subtitle: 'Mathématiques des images' },
  { id: 3, title: 'Partie III', subtitle: 'Manipulation fondamentale' },
  { id: 4, title: 'Partie IV', subtitle: 'Filtrage & amélioration' },
  { id: 5, title: 'Partie V', subtitle: 'Segmentation & features' },
  { id: 6, title: 'Partie VI', subtitle: 'Compréhension d’image' },
  { id: 7, title: 'Partie VII', subtitle: 'IA & Deep Learning' },
  { id: 8, title: 'Partie VIII', subtitle: 'Traitement avancé' },
  { id: 9, title: 'Partie IX', subtitle: 'Implémentation' },
  { id: 10, title: 'Partie X', subtitle: 'Théorie avancée' },
]

export const imageChapters: (ChapterMeta & { level: number })[] = [
  {
    id: 'img0',
    slug: 'introduction',
    number: 0,
    level: 1,
    title: 'Plan du cours — Images numériques',
    description: 'Objectifs, progression scientifique et panorama complet.',
    icon: BookOpen,
  },
  {
    id: 'img1',
    slug: 'nature-image-pixel',
    number: 1,
    level: 1,
    title: 'Nature physique et mathématique d’une image',
    description: 'Pixel, matrice I(x,y), types, résolution et compression.',
    icon: Grid3x3,
  },
  {
    id: 'img2',
    slug: 'algebre-lineaire-images',
    number: 2,
    level: 2,
    title: 'Algèbre linéaire pour les images',
    description: 'Matrices, tenseurs, vecteurs couleur et distances.',
    icon: Layers,
  },
  {
    id: 'img3',
    slug: 'statistiques-images',
    number: 3,
    level: 2,
    title: 'Statistiques appliquées aux images',
    description: 'Histogrammes, moyenne, variance, entropie et bruit.',
    icon: LineChart,
  },
  {
    id: 'img4',
    slug: 'manipulation-pixel',
    number: 4,
    level: 3,
    title: 'Manipulations pixel par pixel',
    description: 'Luminosité, contraste, seuillage et gamma.',
    icon: Zap,
  },
  {
    id: 'img5',
    slug: 'transformations-geometriques',
    number: 5,
    level: 3,
    title: 'Transformations géométriques',
    description: 'Translation, rotation, échelle et interpolation.',
    icon: Shapes,
  },
  {
    id: 'img6',
    slug: 'filtres-spatiaux',
    number: 6,
    level: 4,
    title: 'Filtres spatiaux',
    description: 'Convolution, flou, contours et débruitage.',
    icon: Filter,
  },
  {
    id: 'img7',
    slug: 'domaine-frequentiel',
    number: 7,
    level: 4,
    title: 'Domaine fréquentiel',
    description: 'Fourier, spectre, filtres et JPEG/DCT.',
    icon: Waves,
  },
  {
    id: 'img8',
    slug: 'segmentation-image',
    number: 8,
    level: 5,
    title: 'Segmentation d’image',
    description: 'Seuillage, Otsu, watershed et K-means.',
    icon: Scan,
  },
  {
    id: 'img9',
    slug: 'detection-caracteristiques',
    number: 9,
    level: 5,
    title: 'Détection de caractéristiques',
    description: 'Coins, SIFT, Canny, texture et moments.',
    icon: Target,
  },
  {
    id: 'img10',
    slug: 'reconnaissance-objets',
    number: 10,
    level: 6,
    title: 'Analyse et reconnaissance d’objets',
    description: 'Classification, détection, tracking, visage et OCR.',
    icon: Box,
  },
  {
    id: 'img11',
    slug: 'vision-3d',
    number: 11,
    level: 6,
    title: 'Vision 3D',
    description: 'Caméra pinhole, stéréovision et depth maps.',
    icon: Camera,
  },
  {
    id: 'img12',
    slug: 'deep-learning-visuel-intro',
    number: 12,
    level: 7,
    title: 'Introduction au Deep Learning visuel',
    description: 'Neurones, gradient et fonction de coût.',
    icon: Brain,
  },
  {
    id: 'img13',
    slug: 'reseaux-convolutifs-cnn',
    number: 13,
    level: 7,
    title: 'Réseaux convolutifs (CNN)',
    description: 'Convolution profonde, pooling et architectures.',
    icon: Cpu,
  },
  {
    id: 'img14',
    slug: 'segmentation-detection-avancees',
    number: 14,
    level: 8,
    title: 'Segmentation et détection avancées',
    description: 'U-Net, YOLO, R-CNN et Vision Transformers.',
    icon: Sparkles,
  },
  {
    id: 'img15',
    slug: 'generation-restauration',
    number: 15,
    level: 8,
    title: 'Génération et restauration d’images',
    description: 'Super-résolution, GANs et diffusion.',
    icon: FlaskConical,
  },
  {
    id: 'img16',
    slug: 'applications-modernes',
    number: 16,
    level: 8,
    title: 'Applications modernes',
    description: 'Médecine, satellites, véhicules autonomes, AR…',
    icon: Eye,
  },
  {
    id: 'img17',
    slug: 'opencv-complet',
    number: 17,
    level: 9,
    title: 'OpenCV complet',
    description: 'Lecture, filtres, contours et webcam.',
    icon: Code,
  },
  {
    id: 'img18',
    slug: 'projet-final-vision',
    number: 18,
    level: 9,
    title: 'Projet final de vision par ordinateur',
    description: 'Détecteur de visages, OCR, surveillance, classification…',
    icon: Target,
  },
  {
    id: 'img19',
    slug: 'theorie-mathematique-avancee',
    number: 19,
    level: 10,
    title: 'Théorie mathématique avancée',
    description: 'Information, optimisation et probabilités bayésiennes.',
    icon: BookOpen,
  },
]

export function getImageChapter(slug: string) {
  return imageChapters.find((c) => c.slug === slug)
}

export function imageChaptersByLevel(level: number) {
  return imageChapters.filter((c) => c.level === level)
}
