/** Explications pédagogiques — en complément des puces du plan (jamais en remplacement). */
export const imageSectionExplanations: Record<string, string[]> = {
  '1.1': [
    'Physiquement, une image enregistre l’énergie lumineuse arrivant sur un capteur : réflexion, absorption et source de lumière déterminent ce que l’on voit.',
    'La formation d’image suit le modèle optique : rayons, lentille, plan image — comme l’œil ou une caméra.',
    'La vision machine ne « voit » pas : elle manipule des nombres ; l’interprétation est confiée aux algorithmes.',
    'Le passage analogique → numérique (échantillonnage + quantification) rend l’image traitable par ordinateur.',
  ],
  '1.2': [
    'Le pixel (picture element) est l’unité discrète : une case du tableau.',
    'On repère un pixel par (x, y) ; attention aux conventions (origine, ordre ligne/colonne).',
    'L’intensité quantifie la luminance ou la couleur à cet emplacement.',
    'En mémoire, chaque valeur est un entier binaire (souvent 0–255 sur 8 bits).',
  ],
  '1.3': [
    'La notation I(x, y) formalise l’image comme une fonction discrète sur une grille.',
    'La matrice est la structure concrète stockée en RAM : lignes, colonnes, canaux éventuels.',
  ],
  '1.4': [
    'Binaire : masques, silhouettes. Niveaux de gris : un canal. RGB/RGBA : affichage et transparence.',
    'Multispectrale / hyperspectrale : plusieurs longueurs d’onde — télédétection, science.',
  ],
  '1.5': [
    'Résolution spatiale = nombre de pixels. DPI/PPI lie pixel et taille physique à l’impression.',
    'Taille fichier ≈ largeur × hauteur × canaux × octets par pixel.',
  ],
  '1.6': [
    'PNG : sans perte. JPEG : DCT + quantification, perte visuelle acceptable. WebP : moderne, web.',
    'Sans perte : réversible ; avec perte : plus compact, irréversible.',
  ],
  '2.1': [
    'Une image grise est une matrice ; une image couleur un tenseur (hauteur × largeur × canaux).',
    'En deep learning, un lot d’images forme un tenseur 4D (N, H, W, C).',
  ],
  '2.2': [
    'Addition pixel à pixel : fusion, moyenne d’images.',
    'Multiplication : transformations linéaires, attention.',
    'Transposition : permutation des axes du tenseur.',
  ],
  '2.4': [
    'Distance euclidienne entre vecteurs couleur ou positions.',
    'Similarité : seuillage, clustering, recherche de patchs.',
  ],
  '2.5': [
    'Les combinaisons linéaires d’images (moyennes, interpolations) vivent dans un espace vectoriel de grande dimension.',
  ],
  '5.6': [
    'Nearest neighbor : rapide, effet d’escalier.',
    'Bilinéaire : compromis qualité/vitesse.',
    'Bicubique : meilleure qualité pour zoom.',
  ],
  '3.4': ['Forme de l’histogramme : symétrique, bimodal, étalée — diagnostic rapide d’une image.'],
  '3.5': ['L’entropie mesure le désordre ; utile en compression et en segmentation.'],
  '3.6': ['Modèles de bruit : gaussien, poivre-et-sel, Poisson — pour le débruitage.'],
  '4.1': ['Inversion : négatif, mise en évidence de détails sombres.'],
  '4.2': ['Ajout/multiplication d’une constante — attention à la saturation [0, 255].'],
  '4.3': ['Étirement de contraste entre min et max observés.'],
  '4.5': ['Réduction du nombre de niveaux — effet poster.'],
  '4.6': ['Normalisation : [0,1] ou z-score — prérequis à l’entraînement de réseaux.'],
  '4.7': ['Correction gamma : compenser la non-linéarité des écrans et capteurs.'],
  '5.1': ['Translation : décaler l’image ; bords à remplir.'],
  '5.2': ['Rotation : angle θ ; rééchantillonnage obligatoire.'],
  '5.3': ['Zoom avant/arrière ; aliasing si sous-échantillonnage.'],
  '5.4': ['Miroir horizontal/vertical — augmentation de données.'],
  '5.5': ['Cisaillement : déformation parallélogramme.'],
  '6.2': ['Le noyau (kernel) définit l’effet : flou, dérivée, accentuation.'],
  '6.3': ['Gaussien : lissage isotrope, réduction de bruit.'],
  '6.5': ['Sharpening : renforce les hautes fréquences spatiales.'],
  '7.1': ['Toute image peut se décomposer en sinusoïdes 2D de fréquences variées.'],
  '7.3': ['Spectre : centre = basses fréquences, bords = détails et bruit.'],
  '7.5': ['JPEG exploite la concentration d’énergie en basses fréquences (DCT).'],
  '7.6': ['DCT sur blocs 8×8, quantification, codage entropique.'],
  '8.1': ['Un seul seuil global sur l’histogramme.'],
  '8.2': ['Otsu : seuil optimal automatique (variance inter-classes).'],
  '8.3': ['Region growing : partir de graines.'],
  '8.4': ['Watershed : lignes de séparation entre « bassins ».'],
  '8.5': ['Clustering des couleurs/descripteurs en K groupes.'],
  '8.6': ['Fermer des contours pour obtenir des régions.'],
  '9.4': ['Texture : motifs répétitifs (LBP, Gabor, co-occurrence).'],
  '9.5': ['Moments : description de forme invariante.'],
  '9.6': ['Hough, etc. : droites, cercles dans l’image.'],
  '10.1': ['Attribuer une classe à l’image entière.'],
  '10.2': ['Boîtes + classes (YOLO, R-CNN…).'],
  '10.3': ['Où se trouve l’objet (bbox ou masque).'],
  '10.4': ['Suivi temporel frame à frame.'],
  '10.5': ['Détection + embedding + base de visages.'],
  '10.6': ['Pipeline OCR : détection texte + reconnaissance.'],
  '11.1': ['Homographie, géométrie multi-vues.'],
  '11.3': ['Matrice intrinsèque K : focale, centre, distortion.'],
  '11.4': ['Deux vues → disparité → profondeur.'],
  '11.5': ['Nuage de points, mesh 3D.'],
  '11.6': ['Carte de profondeur par pixel.'],
  '12.1': ['Neurone : somme pondérée + activation.'],
  '12.2': ['Empilement de couches, apprentissage des poids.'],
  '12.3': ['Gradient descent pour minimiser la perte.'],
  '12.4': ['Cross-entropy, MSE, pertes spécialisées.'],
  '13.1': ['Filtres appris, partagés sur l’image.'],
  '13.2': ['Réduction de résolution spatiale.'],
  '13.3': ['Cartes d’activation = motifs détectés.'],
  '13.5': ['Rétropropagation à travers conv et FC.'],
  '14.1': ['U-Net : encodeur-décodeur, segmentation médicale.'],
  '14.2': ['YOLO : détection temps réel.'],
  '14.3': ['Faster R-CNN : proposals + classif.'],
  '14.4': ['Mask R-CNN : masque par instance.'],
  '14.5': ['ViT : patches + transformers.'],
  '15.1': ['SRCNN, ESRGAN : imagerie haute résolution.'],
  '15.2': ['Remplir des zones manquantes.'],
  '15.3': ['DnCNN et modèles dédiés.'],
  '15.4': ['GAN : générateur vs discriminateur.'],
  '15.5': ['Diffusion : bruit puis débruitage appris.'],
  '16.1': ['Imagerie médicale assistée.'],
  '16.2': ['Observation terre, agriculture.'],
  '16.3': ['Biométrie, contrôle d’accès.'],
  '16.4': ['Perception pour conduite autonome.'],
  '16.5': ['Manipulation, SLAM.'],
  '16.6': ['AR : calibrage + overlay 3D.'],
  '16.7': ['Deepfakes, détection de falsification.'],
  '16.8': ['Contrôle qualité industriel.'],
  '17.1': ['cv2.imread, imshow — BGR vs RGB.'],
  '17.2': ['ROI, masques, accès pixel.'],
  '17.3': ['filter2D, GaussianBlur…'],
  '17.4': ['Canny, findContours.'],
  '17.5': ['Pipeline temps réel < 33 ms pour 30 FPS.'],
  '17.6': ['VideoCapture webcam.'],
  '17.7': ['Module dnn, ONNX.'],
  '19.1': ['Quantifier l’information dans un signal.'],
  '19.2': ['H(X) = −Σ p log p.'],
  '19.3': ['Minimisation sous contraintes.'],
  '19.4': ['Courbure, surfaces en 3D.'],
  '19.5': ['Énergies à minimiser (TV, snakes).'],
  '19.6': ['Inférence bayésienne en vision.'],
}
